CREATE TABLE IF NOT EXISTS job_history (
    EMPLOYEE_ID DECIMAL(6,0) NOT NULL PRIMARY KEY,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    DEPARTMENT_ID DECIMAL(4,0) DEFAULT NULL,

    FOREIGN KEY (JOB_ID)
        REFERENCES jobs(JOB_ID)
) ENGINE=InnoDB;
