CREATE TABLE IF NOT EXISTS employees (
    EMPLOYEE_ID DECIMAL(6,0) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(20) DEFAULT NULL,
    LAST_NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(25) NOT NULL,
    PHONE_NUMBER VARCHAR(20) DEFAULT NULL,
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    SALARY DECIMAL(8,2) DEFAULT NULL,
    COMMISSION_PCT DECIMAL(2,2) DEFAULT NULL,
    MANAGER_ID DECIMAL(6,0) DEFAULT NULL,
    DEPARTMENT_ID DECIMAL(4,0) DEFAULT NULL,

    FOREIGN KEY (DEPARTMENT_ID, MANAGER_ID)
        REFERENCES departments(DEPARTMENT_ID, MANAGER_ID)
) ENGINE=InnoDB;
