CREATE TABLE IF NOT EXISTS employees (
    EMPLOYEE_ID DECIMAL(6,0) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(20) DEFAULT NULL,
    LAST_NAME VARCHAR(25) NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    SALARY DECIMAL(8,2) DEFAULT NULL,

    FOREIGN KEY (JOB_ID)
        REFERENCES jobs(JOB_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB;
